# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_songs_is_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_logo',
        ),
    ]
